### ISSUE TITLE
not auto-closing Jinja brackets when nested in quotes

### ISSUE THREAD

**Issue by chillum** [VSChina/vscode-ansible#177]
## Environment
- Extension version: 0.4.0
- OS Type: Windows

## Summary

It would be very nice if Ansible mode supported bracket completion within quotes. This is a common use case (doesn't work without quotes):
```yaml
- synchronize:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
  with_items: '{{some_files}}'
```

unfortunately, Ansible-mode does not auto-close the Jinja brackets inside quoted strings.

## Reproduce steps

* create a file. set mode to Ansible
* enter: `'{{ [ctrl+enter] "{{`

## Expected Results

```yaml
'{{}}'
"{{}}"
```

## Actual Results

```yaml
'{{'
"{{"
```
