### ISSUE TITLE
Feature Request: Linting support

### ISSUE THREAD

**Issue by smiller171** [VSChina/vscode-ansible#232]
## Environment
- Extension version: 0.5.2
- OS Type: MacOS

## Summary
Request to integrate `ansible-lint` into the Ansible VSCode extension

## Reproduce steps
```yaml
---
- hosts: localhost
  connection: local
  vars:
    throw_error: true
  tasks:
  - debug:
      msg: "This should throw a linter error"
    when: throw_error = true
```

## Expected Results

Linter Error should be highlighted in the editor and appear in the "Problems" tab

## Actual Results

VSCode doesn't know there's a linter error
