### ISSUE TITLE
Does not work with k8s module

### ISSUE THREAD

**Issue by mikkeschiren** [VSChina/vscode-ansible#258]
##  Environment
- Extension version: 0.5.2
- OS Type:Linux

## Summary
When editing yaml files, using the k8s module, the extension seems not to understand anything more than k8s, everything else seems not to work, like autocmpletion, this makes the plugin not usable for working with k8s.

https://docs.ansible.com/ansible/latest/modules/k8s_module.html

## Reproduce steps
Enable the extension, open up or edit an ansible file using the k8s module. add:

```
- name: Test
  k8s:
    definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: 'foo'
          namespace: 'bar'
```

## Expected Results
Auto completion should work for definition, and everything below it.

## Actual Results
No auto-completion, and no help availble in the UI.
