### ISSUE TITLE
package module should be allowed to have name parameter of type list

### ISSUE THREAD

**Issue by tjanez** [VSChina/vscode-ansible#260]
## Environment
- Extension version: 0.5.2
- OS Type: Linux

## Summary

If one uses a code snippet like:
```yaml
- name: install the latest version of Apache and MariaDB
  package:
    name:
      - httpd
      - mariadb-server
    state: latest
```
he would get an error:

```
Incorrect type. Expected "string".
```

While the [`package` module documentation](https://docs.ansible.com/ansible/2.9/modules/package_module.html#package-module) doesn't explicitly mention this, it is [clear from the Examples section](https://docs.ansible.com/ansible/2.9/modules/package_module.html#examples) that one could also use a list for the `name` parameter.

**Comment by yerzhant** [comment]
I have the same issue. When one have a task in a role with the content:
```
- name: Install required packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
```
Validation error is: `Incorrect type. Expected "string".` Though a playbook, using the role, does play without any issues.
