### ISSUE TITLE
set_fact - Missing property "key_value"

### ISSUE THREAD

**Issue by lsabalo** [VSChina/vscode-ansible#261]
## Environment
- Extension version: 0.5.2
- OS Type: MacOS

## Summary
VS Code wrongly shows an error where set_fact is properly formatted and it doesn't need a "key_value" property.

## Reproduce steps
```yaml
- name: Load configuration for DNS
  set_fact:
    dns_nameservers: "{{ var1 }}"
  when: ('mygroup' in group_names)
```

## Expected Results
No problem reported

## Actual Results
Problem: Missing property "key_value".
