### ISSUE TITLE
Wrong bigip module URL links

### ISSUE THREAD

**Issue by horol** [VSChina/vscode-ansible#277]
## Environment
- Extension version: 0.5.2
- Ansible: 2.9

## Summary

Generated modules URL for bigip_* are (in this example is used module "bigip_partition": 
- generated module url: http://docs.ansible.com/ansible/bigip_partition_module.html. 
- correct module url: https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_partition_module.html

## Reproduce steps

Task example:
````
    - name: Create partition "{{ partition }}" with route domain "{{ route_domain }}"
      bigip_partition:            
        provider: "{{ provider }}"
        route_domain: "{{ route_domain }}"
        name: "{{ partition }}"
      delegate_to: localhost
      tags:
        - partition
````
URL link to module is wrong (see summary).

## Notes
There is older report about incorrect module urls (#269), but I can't say if this is connected to the same issue. In this case issue is connected to collection "f5networks/f5_modules".

Last question: 
Is this extension maintained? Latest version is from 2018.
