### ISSUE TITLE
Validation of unresolved values

### ISSUE THREAD

**Issue by profiprog** [VSChina/vscode-ansible#279]
## Environment
- Extension version: v0.5.2
- OS Type: MacOS

## Summary
There is reported problem for playbook where value should an enum constant,
but actually is a template expression.

## Reproduce steps
Let's have playbook.yml with this tasks: 
```yaml
  - name: mysql - configure
    become: yes
    copy:
      dest: /etc/mysql/mysql.conf.d/o_custom.cnf
      content: |
        [mysqld]
        lower_case_table_names=1
        default-storage-engine=InnoDB
    register: mysql_config
  - name: mysql - start/restart
    become: yes
    service:
      name: mysql
      state: '{{"restarted" if mysql_config.changed else "started"}}'
```
At last line is reported problem because value should be one of "reloaded", "restarted", "started", "stopped",
but there is a template which should resolve the valid value.

## Expected Results
No problem reporting. Just skip this kind of validation when template is detected.

## Actual Results
`Value is not accepted. Valid values: "reloaded", "restarted", "started", "stopped".`
